sudo: false
language: ruby

rvm:
- 2.7
- 2.6
- 2.5
- 2.4
- 2.3
- ruby-head
- jruby-9.2.11.1
- truffleruby

matrix:
  allow_failures:
    - rvm: 2.3
    - rvm: ruby-head
    - rvm: truffleruby
    - rvm: jruby-9.2.11.1
#   fast_finish: true
